/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SegurancaEPrivacidadeRouteImport } from './routes/seguranca-e-privacidade'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as MeusCreditosRouteImport } from './routes/meus-creditos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KitsRouteImport } from './routes/kits'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as ExplorarRouteImport } from './routes/explorar'
import { Route as EsqueciSenhaRouteImport } from './routes/esqueci-senha'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as EditarPerfilRouteImport } from './routes/editar-perfil'
import { Route as CreditosRouteImport } from './routes/creditos'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as AdminNotificacoesRouteImport } from './routes/admin.notificacoes'
import { Route as AdminModeracaoRouteImport } from './routes/admin.moderacao'
import { Route as AdminModelosRouteImport } from './routes/admin.modelos'
import { Route as AdminFaturamentoRouteImport } from './routes/admin.faturamento'
import { Route as AdminDropsRouteImport } from './routes/admin.drops'
import { Route as AdminCreditosRouteImport } from './routes/admin.creditos'
import { Route as AdminConfigRouteImport } from './routes/admin.config'
import { Route as AdminAvataresRouteImport } from './routes/admin.avatares'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as ApiPublicGooglePlayWebhookRouteImport } from './routes/api/public/google-play-webhook'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SegurancaEPrivacidadeRoute = SegurancaEPrivacidadeRouteImport.update({
  id: '/seguranca-e-privacidade',
  path: '/seguranca-e-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const MeusCreditosRoute = MeusCreditosRouteImport.update({
  id: '/meus-creditos',
  path: '/meus-creditos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KitsRoute = KitsRouteImport.update({
  id: '/kits',
  path: '/kits',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorarRoute = ExplorarRouteImport.update({
  id: '/explorar',
  path: '/explorar',
  getParentRoute: () => rootRouteImport,
} as any)
const EsqueciSenhaRoute = EsqueciSenhaRouteImport.update({
  id: '/esqueci-senha',
  path: '/esqueci-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const EditarPerfilRoute = EditarPerfilRouteImport.update({
  id: '/editar-perfil',
  path: '/editar-perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditosRoute = CreditosRouteImport.update({
  id: '/creditos',
  path: '/creditos',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificacoesRoute = AdminNotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModeracaoRoute = AdminModeracaoRouteImport.update({
  id: '/moderacao',
  path: '/moderacao',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModelosRoute = AdminModelosRouteImport.update({
  id: '/modelos',
  path: '/modelos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFaturamentoRoute = AdminFaturamentoRouteImport.update({
  id: '/faturamento',
  path: '/faturamento',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDropsRoute = AdminDropsRouteImport.update({
  id: '/drops',
  path: '/drops',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCreditosRoute = AdminCreditosRouteImport.update({
  id: '/creditos',
  path: '/creditos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfigRoute = AdminConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAvataresRoute = AdminAvataresRouteImport.update({
  id: '/avatares',
  path: '/avatares',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicGooglePlayWebhookRoute =
  ApiPublicGooglePlayWebhookRouteImport.update({
    id: '/api/public/google-play-webhook',
    path: '/api/public/google-play-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/creditos': typeof CreditosRoute
  '/editar-perfil': typeof EditarPerfilRoute
  '/editor': typeof EditorRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/explorar': typeof ExplorarRoute
  '/historico': typeof HistoricoRoute
  '/kits': typeof KitsRoute
  '/login': typeof LoginRoute
  '/meus-creditos': typeof MeusCreditosRoute
  '/perfil': typeof PerfilRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/seguranca-e-privacidade': typeof SegurancaEPrivacidadeRoute
  '/termos': typeof TermosRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/avatares': typeof AdminAvataresRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/creditos': typeof AdminCreditosRoute
  '/admin/drops': typeof AdminDropsRoute
  '/admin/faturamento': typeof AdminFaturamentoRoute
  '/admin/modelos': typeof AdminModelosRoute
  '/admin/moderacao': typeof AdminModeracaoRoute
  '/admin/notificacoes': typeof AdminNotificacoesRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/google-play-webhook': typeof ApiPublicGooglePlayWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/creditos': typeof CreditosRoute
  '/editar-perfil': typeof EditarPerfilRoute
  '/editor': typeof EditorRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/explorar': typeof ExplorarRoute
  '/historico': typeof HistoricoRoute
  '/kits': typeof KitsRoute
  '/login': typeof LoginRoute
  '/meus-creditos': typeof MeusCreditosRoute
  '/perfil': typeof PerfilRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/seguranca-e-privacidade': typeof SegurancaEPrivacidadeRoute
  '/termos': typeof TermosRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/avatares': typeof AdminAvataresRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/creditos': typeof AdminCreditosRoute
  '/admin/drops': typeof AdminDropsRoute
  '/admin/faturamento': typeof AdminFaturamentoRoute
  '/admin/modelos': typeof AdminModelosRoute
  '/admin/moderacao': typeof AdminModeracaoRoute
  '/admin/notificacoes': typeof AdminNotificacoesRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/admin': typeof AdminIndexRoute
  '/api/public/google-play-webhook': typeof ApiPublicGooglePlayWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/creditos': typeof CreditosRoute
  '/editar-perfil': typeof EditarPerfilRoute
  '/editor': typeof EditorRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/explorar': typeof ExplorarRoute
  '/historico': typeof HistoricoRoute
  '/kits': typeof KitsRoute
  '/login': typeof LoginRoute
  '/meus-creditos': typeof MeusCreditosRoute
  '/perfil': typeof PerfilRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/seguranca-e-privacidade': typeof SegurancaEPrivacidadeRoute
  '/termos': typeof TermosRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/avatares': typeof AdminAvataresRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/creditos': typeof AdminCreditosRoute
  '/admin/drops': typeof AdminDropsRoute
  '/admin/faturamento': typeof AdminFaturamentoRoute
  '/admin/modelos': typeof AdminModelosRoute
  '/admin/moderacao': typeof AdminModeracaoRoute
  '/admin/notificacoes': typeof AdminNotificacoesRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/google-play-webhook': typeof ApiPublicGooglePlayWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cadastro'
    | '/configuracoes'
    | '/creditos'
    | '/editar-perfil'
    | '/editor'
    | '/esqueci-senha'
    | '/explorar'
    | '/historico'
    | '/kits'
    | '/login'
    | '/meus-creditos'
    | '/perfil'
    | '/privacidade'
    | '/reset-password'
    | '/seguranca-e-privacidade'
    | '/termos'
    | '/admin/analytics'
    | '/admin/avatares'
    | '/admin/config'
    | '/admin/creditos'
    | '/admin/drops'
    | '/admin/faturamento'
    | '/admin/modelos'
    | '/admin/moderacao'
    | '/admin/notificacoes'
    | '/admin/usuarios'
    | '/admin/'
    | '/api/public/google-play-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/configuracoes'
    | '/creditos'
    | '/editar-perfil'
    | '/editor'
    | '/esqueci-senha'
    | '/explorar'
    | '/historico'
    | '/kits'
    | '/login'
    | '/meus-creditos'
    | '/perfil'
    | '/privacidade'
    | '/reset-password'
    | '/seguranca-e-privacidade'
    | '/termos'
    | '/admin/analytics'
    | '/admin/avatares'
    | '/admin/config'
    | '/admin/creditos'
    | '/admin/drops'
    | '/admin/faturamento'
    | '/admin/modelos'
    | '/admin/moderacao'
    | '/admin/notificacoes'
    | '/admin/usuarios'
    | '/admin'
    | '/api/public/google-play-webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cadastro'
    | '/configuracoes'
    | '/creditos'
    | '/editar-perfil'
    | '/editor'
    | '/esqueci-senha'
    | '/explorar'
    | '/historico'
    | '/kits'
    | '/login'
    | '/meus-creditos'
    | '/perfil'
    | '/privacidade'
    | '/reset-password'
    | '/seguranca-e-privacidade'
    | '/termos'
    | '/admin/analytics'
    | '/admin/avatares'
    | '/admin/config'
    | '/admin/creditos'
    | '/admin/drops'
    | '/admin/faturamento'
    | '/admin/modelos'
    | '/admin/moderacao'
    | '/admin/notificacoes'
    | '/admin/usuarios'
    | '/admin/'
    | '/api/public/google-play-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  CreditosRoute: typeof CreditosRoute
  EditarPerfilRoute: typeof EditarPerfilRoute
  EditorRoute: typeof EditorRoute
  EsqueciSenhaRoute: typeof EsqueciSenhaRoute
  ExplorarRoute: typeof ExplorarRoute
  HistoricoRoute: typeof HistoricoRoute
  KitsRoute: typeof KitsRoute
  LoginRoute: typeof LoginRoute
  MeusCreditosRoute: typeof MeusCreditosRoute
  PerfilRoute: typeof PerfilRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SegurancaEPrivacidadeRoute: typeof SegurancaEPrivacidadeRoute
  TermosRoute: typeof TermosRoute
  ApiPublicGooglePlayWebhookRoute: typeof ApiPublicGooglePlayWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seguranca-e-privacidade': {
      id: '/seguranca-e-privacidade'
      path: '/seguranca-e-privacidade'
      fullPath: '/seguranca-e-privacidade'
      preLoaderRoute: typeof SegurancaEPrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meus-creditos': {
      id: '/meus-creditos'
      path: '/meus-creditos'
      fullPath: '/meus-creditos'
      preLoaderRoute: typeof MeusCreditosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kits': {
      id: '/kits'
      path: '/kits'
      fullPath: '/kits'
      preLoaderRoute: typeof KitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorar': {
      id: '/explorar'
      path: '/explorar'
      fullPath: '/explorar'
      preLoaderRoute: typeof ExplorarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esqueci-senha': {
      id: '/esqueci-senha'
      path: '/esqueci-senha'
      fullPath: '/esqueci-senha'
      preLoaderRoute: typeof EsqueciSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editar-perfil': {
      id: '/editar-perfil'
      path: '/editar-perfil'
      fullPath: '/editar-perfil'
      preLoaderRoute: typeof EditarPerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creditos': {
      id: '/creditos'
      path: '/creditos'
      fullPath: '/creditos'
      preLoaderRoute: typeof CreditosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notificacoes': {
      id: '/admin/notificacoes'
      path: '/notificacoes'
      fullPath: '/admin/notificacoes'
      preLoaderRoute: typeof AdminNotificacoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/moderacao': {
      id: '/admin/moderacao'
      path: '/moderacao'
      fullPath: '/admin/moderacao'
      preLoaderRoute: typeof AdminModeracaoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/modelos': {
      id: '/admin/modelos'
      path: '/modelos'
      fullPath: '/admin/modelos'
      preLoaderRoute: typeof AdminModelosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/faturamento': {
      id: '/admin/faturamento'
      path: '/faturamento'
      fullPath: '/admin/faturamento'
      preLoaderRoute: typeof AdminFaturamentoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/drops': {
      id: '/admin/drops'
      path: '/drops'
      fullPath: '/admin/drops'
      preLoaderRoute: typeof AdminDropsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/creditos': {
      id: '/admin/creditos'
      path: '/creditos'
      fullPath: '/admin/creditos'
      preLoaderRoute: typeof AdminCreditosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/config': {
      id: '/admin/config'
      path: '/config'
      fullPath: '/admin/config'
      preLoaderRoute: typeof AdminConfigRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/avatares': {
      id: '/admin/avatares'
      path: '/avatares'
      fullPath: '/admin/avatares'
      preLoaderRoute: typeof AdminAvataresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/google-play-webhook': {
      id: '/api/public/google-play-webhook'
      path: '/api/public/google-play-webhook'
      fullPath: '/api/public/google-play-webhook'
      preLoaderRoute: typeof ApiPublicGooglePlayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAvataresRoute: typeof AdminAvataresRoute
  AdminConfigRoute: typeof AdminConfigRoute
  AdminCreditosRoute: typeof AdminCreditosRoute
  AdminDropsRoute: typeof AdminDropsRoute
  AdminFaturamentoRoute: typeof AdminFaturamentoRoute
  AdminModelosRoute: typeof AdminModelosRoute
  AdminModeracaoRoute: typeof AdminModeracaoRoute
  AdminNotificacoesRoute: typeof AdminNotificacoesRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAvataresRoute: AdminAvataresRoute,
  AdminConfigRoute: AdminConfigRoute,
  AdminCreditosRoute: AdminCreditosRoute,
  AdminDropsRoute: AdminDropsRoute,
  AdminFaturamentoRoute: AdminFaturamentoRoute,
  AdminModelosRoute: AdminModelosRoute,
  AdminModeracaoRoute: AdminModeracaoRoute,
  AdminNotificacoesRoute: AdminNotificacoesRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CadastroRoute: CadastroRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  CreditosRoute: CreditosRoute,
  EditarPerfilRoute: EditarPerfilRoute,
  EditorRoute: EditorRoute,
  EsqueciSenhaRoute: EsqueciSenhaRoute,
  ExplorarRoute: ExplorarRoute,
  HistoricoRoute: HistoricoRoute,
  KitsRoute: KitsRoute,
  LoginRoute: LoginRoute,
  MeusCreditosRoute: MeusCreditosRoute,
  PerfilRoute: PerfilRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SegurancaEPrivacidadeRoute: SegurancaEPrivacidadeRoute,
  TermosRoute: TermosRoute,
  ApiPublicGooglePlayWebhookRoute: ApiPublicGooglePlayWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
